### ISSUE TITLE
Instructions for filing an Issue on this gitbook

### ISSUE THREAD

**Issue by stephwright** [mozillascience/study-group-onboarding#28]
First page of the Gitbook says:
Help us grow and improve this book!
Check out the "issues" tab, above, to see what you can do to improve or add to these materials. We'd love your help!

But the "issues" tab isn't visible inside the gitbook... only in the repository.  How do we want to direct folks to file issues?

**Comment by RaoOfPhysics** [comment]
Should we simply link to the issues page on GitHub?

**Comment by zee-moz** [comment]
@stephwright @RaoOfPhysics 
I've added a link to the issues tab-- I think some of that language was carried over from the pre-GitBook version. Thanks for the fix! 😺
